[MeterBar0]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
[MeterBar1]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
[MeterBar2]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
[MeterBar3]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
[MeterBar4]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
[MeterBar5]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
[MeterBar6]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
[MeterBar7]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
[MeterBar8]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
[MeterBar9]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
[MeterBar10]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
[MeterBar11]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]
[MeterBar12]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed12
TransformationMatrix=[Matrix]
[MeterBar13]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed13
TransformationMatrix=[Matrix]
[MeterBar14]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed14
TransformationMatrix=[Matrix]
[MeterBar15]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed15
TransformationMatrix=[Matrix]
[MeterBar16]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed16
TransformationMatrix=[Matrix]
[MeterBar17]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed17
TransformationMatrix=[Matrix]
[MeterBar18]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed18
TransformationMatrix=[Matrix]
[MeterBar19]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed19
TransformationMatrix=[Matrix]
[MeterBar20]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed20
TransformationMatrix=[Matrix]
[MeterBar21]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed21
TransformationMatrix=[Matrix]
[MeterBar22]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed22
TransformationMatrix=[Matrix]
[MeterBar23]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed23
TransformationMatrix=[Matrix]
[MeterBar24]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed24
TransformationMatrix=[Matrix]
[MeterBar25]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed25
TransformationMatrix=[Matrix]
[MeterBar26]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed26
TransformationMatrix=[Matrix]
[MeterBar27]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed27
TransformationMatrix=[Matrix]
[MeterBar28]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed28
TransformationMatrix=[Matrix]
[MeterBar29]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed29
TransformationMatrix=[Matrix]
[MeterBar30]
Meter=BAR
BarColor=#Color#
Group=GroupBars | GroupDynamicColors
MeasureName=MeasureAudioSmoothed30
TransformationMatrix=[Matrix]