[MeterShadowBar0]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed0
TransformationMatrix=[Matrix]
[MeterShadowBar1]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed1
TransformationMatrix=[Matrix]
[MeterShadowBar2]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed2
TransformationMatrix=[Matrix]
[MeterShadowBar3]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed3
TransformationMatrix=[Matrix]
[MeterShadowBar4]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed4
TransformationMatrix=[Matrix]
[MeterShadowBar5]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed5
TransformationMatrix=[Matrix]
[MeterShadowBar6]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed6
TransformationMatrix=[Matrix]
[MeterShadowBar7]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed7
TransformationMatrix=[Matrix]
[MeterShadowBar8]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed8
TransformationMatrix=[Matrix]
[MeterShadowBar9]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed9
TransformationMatrix=[Matrix]
[MeterShadowBar10]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed10
TransformationMatrix=[Matrix]
[MeterShadowBar11]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed11
TransformationMatrix=[Matrix]
[MeterShadowBar12]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed12
TransformationMatrix=[Matrix]
[MeterShadowBar13]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed13
TransformationMatrix=[Matrix]
[MeterShadowBar14]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed14
TransformationMatrix=[Matrix]
[MeterShadowBar15]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed15
TransformationMatrix=[Matrix]
[MeterShadowBar16]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed16
TransformationMatrix=[Matrix]
[MeterShadowBar17]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed17
TransformationMatrix=[Matrix]
[MeterShadowBar18]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed18
TransformationMatrix=[Matrix]
[MeterShadowBar19]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed19
TransformationMatrix=[Matrix]
[MeterShadowBar20]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed20
TransformationMatrix=[Matrix]
[MeterShadowBar21]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed21
TransformationMatrix=[Matrix]
[MeterShadowBar22]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed22
TransformationMatrix=[Matrix]
[MeterShadowBar23]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed23
TransformationMatrix=[Matrix]
[MeterShadowBar24]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed24
TransformationMatrix=[Matrix]
[MeterShadowBar25]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed25
TransformationMatrix=[Matrix]
[MeterShadowBar26]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed26
TransformationMatrix=[Matrix]
[MeterShadowBar27]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed27
TransformationMatrix=[Matrix]
[MeterShadowBar28]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed28
TransformationMatrix=[Matrix]
[MeterShadowBar29]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed29
TransformationMatrix=[Matrix]
[MeterShadowBar30]
Meter=BAR
BarColor=#DropShadowColor#
Group=GroupBars | GroupShadowBars
MeasureName=MeasureAudioSmoothed30
TransformationMatrix=[Matrix]