
[Variables]

Font1=Alien League

WeatherIcons=#ROOTCONFIGPATH#\@Resources\Weathericons

Zipcode=UKXX0085

Language=English

Tscale=m
TempScale=C
ScaleUnit=°C

Color1=198,229,255
Color2=0,255,255
Color3=255,150,150
color4=228,129,255
color5=255,187,125

color=Orange

ics=255,187,125

Launcher1=www.twitter.com
Launcher2=www.facebook.com
Launcher3=www.youtube.com
Launcher4=www.reddit.com
Launcher5=chrome.exe
Launcher6=steam.exe
Launcher7=www.gmail.com
Launcher8=itunes.exe

sound.wav=rainforest

Hour=H
